blueprint:
  source_url: https://raw.githubusercontent.com/cyberjunky/home-assistant-fireservicerota/master/blueprints/automation/fireservicerota/incident_tts.yaml
  name: FireServiceRota Text to Speech
  description: Broadcast Incident TTS at incident call
  domain: automation
  input:
    incidents_sensor:
      name: Incidents Sensor
      default: 'sensor.incidents'
      description: The standard incident sensor added by FireServiceRota. Please select the correct one if you changed the entity name of the sensor.
      selector:
        entity:
          integration: fireservicerota
          domain: sensor
    duty_binary_sensor:
      name: Duty
      default: binary_sensor.duty
      description: Please choose your duty sensor if you changed the entity name
      selector:
        entity:
          integration: fireservicerota
          domain: binary_sensor
    person_at_home:
      name: User
      default: person.me
      description: Select the person, automation will only work if person is home.
      selector:
        entity:
          domain: person
    active_zone:
      name: Zone
      default: zone.home
      description: If the user is in this zone the automation will run.
      selector:
        entity:
          domain: zone
    target_media_player:
      name: Media Player
      description: The Media Player for broadcast.
      selector:
        target:
          entity:
            domain: media_player
    target_media_player_volume:
      name: Media Player Volume
      description: Volume for broadcast.
      default: '0.3'
      selector:
        number:
          min: '0.1'
          max: '1.0'
          step: '0.1'
    execution_start_time:
      name: "Only play announcments from:"
      description: Start Time
      default: '07:00'
      selector:
        time:
    execution_stop_time:
      name: "Mute announcements at:"
      description: End Time
      default: '22:00'
      selector:
        time:

trigger:
  platform: state
  entity_id: !input incidents_sensor

condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input incidents_sensor
        attribute: message_to_speech_url
        state: None
  - condition: state
    entity_id: !input duty_binary_sensor
    state: 'on'
  - condition: zone
    entity_id: !input person_at_home
    zone: !input active_zone
  - condition: time
    after: !input execution_start_time
    before: !input execution_stop_time

action:
  - variables:
      var_incidents_sensor: !input incidents_sensor
  - service: media_player.volume_set
    target: !input 'target_media_player'
    data:
      volume_level: !input 'target_media_player_volume'
  - service: media_player.play_media
    target: !input target_media_player
    data_template:
      media_content_id: >
          {{ state_attr(var_incidents_sensor,'message_to_speech_url') }}
      media_content_type: 'audio/mp4'
