blueprint:
  source_url: https://raw.githubusercontent.com/cyberjunky/home-assistant-fireservicerota/master/blueprints/automation/fireservicerota/incident_tts.yaml
  name: FireServiceRota Text to Speech
  description: Broadcast Incident TTS at incident call
  domain: automation
  input:
    incidents_sensor:
      name: Incidents Sensor
      default: 'sensor.incidents'
      description: The standard incident sensor added by FireServiceRota. Please select the correct one if you changed the entity name of the sensor.
      selector:
        entity:
          integration: fireservicerota
          domain: sensor
    duty_binary_sensor:
      name: Duty
      default: binary_sensor.duty
      description: Please choose your duty sensor if you changed the entity name
      selector:
        entity:
          integration: fireservicerota
          domain: binary_sensor
    target_media_player:
      name: Media Player
      description: The Media Player for broadcast.
      selector:
        target:
          entity:
            domain: media_player
    target_media_player_volume:
      name: Media Player Volume
      description: Volume for broadcast.
      default: '0.3'
      selector:
        number:
          min: '0.1'
          max: '1.0'
          step: '0.1'

trigger:
  platform: state
  entity_id: !input incidents_sensor

condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input incidents_sensor
        attribute: message_to_speech_url
        state: None
  - condition: state
    entity_id: !input duty_binary_sensor
    state: 'on'

action:
  - variables:
      var_incidents_sensor: !input incidents_sensor
  - service: media_player.volume_set
    target: !input 'target_media_player'
    data:
      volume_level: !input 'target_media_player_volume'
  - service: media_player.play_media
    target: !input target_media_player
    data_template:
      media_content_id: >
          {{ state_attr(var_incidents_sensor,message_to_speech_url) }}
      media_content_type: 'audio/mp4'
